### ISSUE TITLE
Error trying to run autosparkle from Terminal (zsh)

### ISSUE THREAD

**Issue by am-play** [hadiidbouk/autosparkle#1]
Hello,

Very excited to experiment with this tool for a Mac app I am distributing! This will really save a lot of time for developers. 

So I am getting an error when trying to run `autosparkle` from zshell. I am not super experienced with Ruby, but it appears the binary is having issues finding dependencies, which do look to be installed. 

I am on a M2 MacBookPro

$PATH looks good. Also the `autosparkle` bin throws the same error without adding the binary to path as specified

`
echo $PATH
/opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.3.0/bin:/Users/andrew/google-cloud-sdk/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.3.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
`

`ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]`

`gem -v
3.5.17`

Tried running both of these: 
`$ /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle distribute --help`
`$ autosparkle distribute --help`

`
$ autosparkle distribute --help
/opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:407:in `block in require_program': program version required (Commander::Runner::CommandError)
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:406:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:406:in `require_program'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:42:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/import.rb:7:in `block in <top (required)>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- Plist (LoadError)
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/packaging.rb:3:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `<main>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- Plist (LoadError)
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/packaging.rb:3:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `<main>'
gem -v
3.5.17
ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
echo $PATH
/opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.3.0/bin:/Users/andrew/google-cloud-sdk/bin:/opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.3.0/bin:/Users/andrew/google-cloud-sdk/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.3.0/bin:/Users/andrew/google-cloud-sdk/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.3.0/bin:/Users/andrew/google-cloud-sdk/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.3.0/bin:/Users/andrew/google-cloud-sdk/bin:/Users/andrew/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
:
/opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle distribute --help
/opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:407:in `block in require_program': program version required (Commander::Runner::CommandError)
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:406:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:406:in `require_program'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/runner.rb:42:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-5.0.0/lib/commander/import.rb:7:in `block in <top (required)>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- Plist (LoadError)
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/packaging.rb:3:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `<main>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- Plist (LoadError)
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/packaging.rb:3:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/lib/autosparkle/main.rb:6:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/autosparkle-0.1.1/bin/autosparkle:3:in `<main>'
`
<img width="1070" alt="Screenshot 2024-08-09 at 8 38 19 PM" src="https://github.com/user-attachments/assets/aca0132f-f4fc-44aa-9e1d-1da8d92991a9">
<img width="1070" alt="Screenshot 2024-08-09 at 8 38 13 PM" src="https://github.com/user-attachments/assets/1e83d225-ce6e-4398-a8a1-e52ca430d241">

**Comment by am-play** [comment]
I figured out the [solution](https://stackoverflow.com/questions/67678955/cannot-load-such-file-plist-catalina-and-xcode-12-4) to the error. Needed to manually install this: 

`gem install plist activesupport xcodeproj`
